<?php
/*
 * This file is part of the php127/websiteinfo.
 *
 * (c) 读心印 <aa24615@qq.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Php127\Tests\Seek;

use Php127\Seek\NameSeek;
use PHPUnit\Framework\TestCase;

/**
 * Class NameSeekTest.
 *
 * @package Php127\Tests\Seek
 *
 * @author 读心印 <aa24615@qq.com>
 */
class NameSeekTest extends TestCase
{
    protected $titles;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $text = file_get_contents('./tests/file/title.txt');

        $this->titles = explode(PHP_EOL, $text);
    }

    public function testFilterStr()
    {
        $str = NameSeek::filterStr("[腾讯网");

        $this->assertTrue($str === "腾讯网");

        $str = NameSeek::filterStr("【腾讯网");

        $this->assertTrue($str === "腾讯网");
    }

    public function testSetStr()
    {
        foreach ($this->titles as $title) {
            $data = NameSeek::setStr($title);
            $this->assertTrue(count($data) > 0);
        }
    }
    public function testFind()
    {
        foreach ($this->titles as $title) {
            $data = NameSeek::find($title);
            $this->assertTrue(strlen($data) > 0);
        }
    }

    public function testXxWang()
    {
        foreach ($this->titles as $title) {
            $data = NameSeek::xxWang($title);
            $this->assertTrue(is_array($data));
        }
    }


    public function testEndStr()
    {
        foreach ($this->titles as $title) {
            $data = NameSeek::endStr($title);
            $this->assertTrue(count($data) > 0);
        }
    }
}
