<?php

/*
 * This file is part of the php127/websiteinfo.
 *
 * (c) 读心印 <aa24615@qq.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Php127\Tests\Seek;

use Php127\Seek\QQSeek;
use PHPUnit\Framework\TestCase;

/**
 * QQSeekTest.
 *
 * @author 读心印 <aa24615@qq.com>
 */
class QQSeekTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->str = '联系qq 32323422 联系扣扣 32323423';
        $this->uin = '<a href="//wpa.qq.com/msgrd?v=3&amp;uin=12606003&amp;site=qq&amp;menu=yes" target="_blank" rel="nofollow">
<a href="//wpa.qq.com/msgrd?v=3&amp;uin=232233&amp;site=qq&amp;menu=yes" target="_blank" rel="nofollow">';
    }


    public function testFind()
    {
        //模糊匹配
        $qq = QQSeek::find($this->uin.$this->str);
        $this->assertTrue(count($qq) == 4);

        //精准匹配
        $qq = QQSeek::find($this->uin.$this->str, 1);
        $this->assertTrue(count($qq) == 2);
    }

    public function testUin()
    {
        $qq = QQSeek::uin($this->uin);
        $this->assertTrue(count($qq) == 2);
    }
    public function testInitial()
    {
        $qq = QQSeek::initial($this->str);
        $this->assertTrue(count($qq) == 2);
    }

    public function testElaboration()
    {
        $qq = QQSeek::elaboration('联系扣扣 32323422');
        $this->assertTrue(!empty($qq));
    }
}
