<?php

namespace Php127\Tests\Seek;

use Php127\WebsiteInfo\Seek\WeiwinSeek;
use PHPUnit\Framework\TestCase;

class WeixinSeekTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->str = "微信客服 aa24615 联系微信 aa23232";
    }

    public function testFind()
    {
        $res = WeiwinSeek::find($this->str);
        $this->assertTrue(count($res) == 2);
    }
}
